[build]
builder = "nixpacks"

[deploy]
buildCommand = "npm ci && npm run db:push && npm run build && cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/"
startCommand = "cd .next/standalone && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"