[build]
builder = "nixpacks"

[deploy]
buildCommand = "npm ci && npm run db:push && npm run build"
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"