[build]
builder = "nixpacks"

[deploy]
buildCommand = "npm ci && npm run db:push && npm run build"
startCommand = "cp -r .next/static .next/standalone/.next/ 2>/dev/null || true && cp -r public .next/standalone/ 2>/dev/null || true && cd .next/standalone && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"